version: '3.4'

services:
  imgauth:
    image: imgauth
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
